server:
  port: 9000

spring:
  datasource:
    url: jdbc:mariadb://39.105.15.234:3306/platform-chaotic?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: Yan0626..
